project:
  type: book
  output-dir: _book

book:
  title: "物联网终端操作系统笔记"
  subtitle: "物联网终端操作系统选修课学习笔记"
  author: "hugswangyu"
  date: "2026-06-23"
  search: true
  repo-url: https://github.com/hugswangyu/iot-os-notes
  page-navigation: true
  chapters:
    - index.qmd
    - ch1_物联网及嵌入式概述.md
    - ch2_ch3_物联网操作系统的关键技术.md
    - ch4_连接技术.md
    - ch5_连接与协议.md
    - ch6_LiteOS操作系统及其移植.md
    - ch7_任务.md
    - ch8_信号量与互斥锁.md
    - ch9_消息队列_事件与软件定时器.md
    - ch10_内存管理与中断管理.md
    - ch11_物联网操作系统的应用案例.md

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: right
    number-sections: false
    anchor-sections: true
    smooth-scroll: true
